//-----------------------------------------------------------------------------
//  Holiday.js is part of the BART dashboard widget.  (c) 2005 Bret Victor
//  This software is licensed under the terms of the open source MIT license.
//-----------------------------------------------------------------------------
//
//  Service Levels -- http://www.bart.gov/guide/holidays.aspx
//
//  Automatically generated by make_holiday.pl on Sat Dec  1 12:43:56 2012.
//

function Holiday () {

    servicelevel = {}
    servicelevel['12/25/2012'] = 'sunday'
    servicelevel['01/01/2013'] = 'sunday'
    servicelevel['01/21/2013'] = 'saturday'
    servicelevel['02/18/2013'] = 'saturday'
    servicelevel['05/27/2013'] = 'sunday'
    servicelevel['07/04/2013'] = 'sunday'
    servicelevel['09/02/2013'] = 'sunday'
    servicelevel['11/28/2013'] = 'sunday'
    servicelevel['12/25/2013'] = 'sunday'
    
    Holiday.getServiceLevel = function(date) {
        var date_string = date.toMMDDYYYYString()
        var day_of_week = date.getDay()
        
        return servicelevel[date_string] ||
            ( (day_of_week == 0)        ? 'sunday'
            : (day_of_week == 6)        ? 'saturday'
            :                             'weekday')
    }
}

// Open the package.
Holiday();

